### ISSUE TITLE
Instant bow charge causing crash

### ISSUE THREAD

**Issue by ansarimerican** [Akebi-Private/Akebi-Issue-Tracker#1]
Hi. I tried to use the instant bow charge with Gorou, and it caused my game to crash twice now.

**Comment by Cloudy293** [comment]
> 

ты че долбоеб у него с этим полная пизда

**Comment by MongMikng** [comment]
Same. I use Tighnari, enabling instant bow will crash the game.

**Comment by romanocry** [comment]
Same for Ganyu character ... It's the main feature i use...

**Comment by Taiga74164** [comment]
fixed, wait for update today
