### ISSUE TITLE
ESP config does not save upon quitting the game

### ISSUE THREAD

**Issue by Beefandleather** [Akebi-Private/Akebi-Issue-Tracker#100]
Any changes made to ESP, like selecting items and changing colors, don't save when you quit the game fully and relog. The new patch did not seem to have solved this issue.

**Comment by trasser** [comment]
The same thing. At the same time, if you select a group, it is written to the configuration. Forever. And any changes are not saved (disabling items one by one, changing colors, etc.)

**Comment by ghost** [comment]
Duplicate #101
