### ISSUE TITLE
`Config`: Some configuration not saving

### ISSUE THREAD

**Issue by stig141** [Akebi-Private/Akebi-Issue-Tracker#101]
This is the original setting of Bao Xiang![@TNYCJBV(VQ%1B I_ XT$RN](https://user-images.githubusercontent.com/18372822/213639365-c526c1e0-8f1a-4c63-bf79-b5f82ad8a904.png)
Then I switched to profile #1
![X)}AW$FW62C`4XEO9LHP AC](https://user-images.githubusercontent.com/18372822/213639628-c6c56e83-51aa-43bb-8963-7fe3e4766f65.png)
I switched back to baoxiang and the settings were reset
![( @NEFV%$JJQCOY(IJUFRLL](https://user-images.githubusercontent.com/18372822/213639763-c959be79-2fe2-4a60-9b56-610d017c85d1.png)

**Comment by djdoolky76** [comment]
That's literally happened to me, you need to recheck them all again when you restart the loader
