### ISSUE TITLE
`Auto Fish` don't work

### ISSUE THREAD

**Issue by SecPhases** [Akebi-Private/Akebi-Issue-Tracker#102]
Fished first one fish,then it doesn't work anymore.Recast the rod or change the pool still doesn't work.
I neeeeeeeed auto fish Even i have to recast rod manually

**Comment by ghost** [comment]
From #93: Fifth, when I automatically fish, the first time is normal. In the second time, I didn't open the new bait, but it seems that it will refresh itself and there is no place to close it. This will cause the fish I need to catch to be disturbed. I don't know how to close the Catch Delay (ms) script
