### ISSUE TITLE
`Auto talk`: Auto talk only with hotkey

### ISSUE THREAD

**Issue by countstars-xing** [Akebi-Private/Akebi-Issue-Tracker#105]
atuo talk use hotkey:
When I use key [atuo talk use hotkey], the conversation will speed up. When I release the key, the conversation still accelerates, just won't continue to the next sentence.

**Comment by djdoolky76** [comment]
there's a new version release in discord and this bug can be fixed right now

**Comment by ghost** [comment]
Already fixed.
