### ISSUE TITLE
quest teleport

### ISSUE THREAD

**Issue by GSwordGCil** [Akebi-Private/Akebi-Issue-Tracker#115]
seems like quest teleport was added according to #6 but there seems to be no option in the Teleport tab or a hotkey that can be bind to it in the Hotkeys tab. please double check, ty! Pressing the default key 'v' also did not do anything in game.

**Comment by Taiga74164** [comment]
added for update tomorrow

**Comment by romanocry** [comment]
tomorrow, during the 21th day ?
