### ISSUE TITLE
Failed to initiate static TLS for image. Error 183

### ISSUE THREAD

**Issue by djdoolky76** [Akebi-Private/Akebi-Issue-Tracker#12]
Can someone help me with this error?

![image](https://user-images.githubusercontent.com/30578879/213261407-d56cba34-ebd4-4874-8901-47285794ae7d.png)

**Comment by LookMomihaveaUsername** [comment]
I fixed it for my self. Create a Shortcut/Linking or how you say it... 
![grafik](https://user-images.githubusercontent.com/123008691/213261830-90248ce7-9d3a-46e1-aa3e-a1807b37e2a9.png)
So it looks like this. Now for me. TRhen open the Shortcut / Linking. In the FIrst bar you see then AkebiLauncher.exe and at to it with a space -analog_inject and save it. Now open this and it should work. 
![grafik](https://user-images.githubusercontent.com/123008691/213262654-147d11e5-ae58-420e-b13a-965d485e082c.png)

**Comment by djdoolky76** [comment]
It works now, thank you

![image](https://user-images.githubusercontent.com/30578879/213263695-89f2e951-541f-4484-8467-fa1f96c5b5fe.png)
