### ISSUE TITLE
`Attack modifiers`: Enemies move with freeze/petrified

### ISSUE THREAD

**Issue by ghost** [Akebi-Private/Akebi-Issue-Tracker#121]
when enemies are "frozen" or hit with Zhongli's Q, they still move. Not sure if this is an issue with the cheat but I noticed it with the recent update

**Comment by Taiga74164** [comment]
fixed on next update 
![image](https://user-images.githubusercontent.com/67109235/213845207-18abd208-d664-4359-97dc-7ed3685feb22.png)
