### ISSUE TITLE
some ESP change won't auto save while you change the settings

### ISSUE THREAD

**Issue by errqww** [Akebi-Private/Akebi-Issue-Tracker#122]
when you use the esp and change the settings about the things to trace, the cheat won't auto save the changes into the cfg.json and you need to manually repeat the step every time you open the game, and it won't auto load the related settings(only esp related settings) in the cfg.json.

**Comment by errqww** [comment]
it seems others have reported the same issue, but not the loading problems, although you have previous settings saving of things in the esp in the cfg.json, the cheat won't load them, just lauch with the initial settings (only the esp settings have this problem)

**Comment by ghost** [comment]
Duplicate #101
