### ISSUE TITLE
Failed to initialize static TLS for image. Error: 183 Cannot create a file when that file already exists.

### ISSUE THREAD

**Issue by LaposLazulia** [Akebi-Private/Akebi-Issue-Tracker#127]
https://cdn.discordapp.com/attachments/1011905367384539176/1066215893115338812/image.png

This happens on running the exe.

**Comment by RyujinZX** [comment]
watch faq video.

**Comment by LaposLazulia** [comment]
Did that, same result.

Edit: Checked the shortcut, somehow the argument got garbled. Fixed it to what it was, working fine now. Ty.

**Comment by Tarkan022** [comment]
Hi, where is the video?

**Comment by RyujinZX** [comment]
> Hi, where is the video?

![image](https://user-images.githubusercontent.com/101382869/213872290-e03f9e80-a6c6-406b-92cd-b68f1ef23981.png)

**Comment by Tarkan022** [comment]
Thanks :))
