### ISSUE TITLE
Enable buried chest in ESP cause game crash

### ISSUE THREAD

**Issue by djdoolky76** [Akebi-Private/Akebi-Issue-Tracker#135]
Some users also get crashes not even the buried chest but some chests look fine to me 
https://user-images.githubusercontent.com/30578879/213869596-a73ff73b-c666-4581-af6c-bd02b7c3e258.mp4

Additional ESP options get crashed:
- Primal Obelisk
- Seelie
- Seelie Lamp
- Relay Stone

**Comment by RyujinZX** [comment]
yes, wait fix
