### ISSUE TITLE
Interactive Map not working

### ISSUE THREAD

**Issue by OneAutumnLeafXiao** [Akebi-Private/Akebi-Issue-Tracker#14]

**Comment by Taiga74164** [comment]
Works fine. click the button on bottom left to show the menu
![GenshinImpact_DCd6KMq9Hj](https://user-images.githubusercontent.com/67109235/213360770-5cad9f67-9cb7-4ecf-a998-7ca7fbc138cd.png)

**Comment by OneAutumnLeafXiao** [comment]
clicking on the button in the left all these options are missing just empty - what am I missing?

![image](https://user-images.githubusercontent.com/122941077/213428586-5cecabae-a5f8-4c14-ae2a-aff718c67f88.png)

**Comment by Taiga74164** [comment]
> clicking on the button in the left all these options are missing just empty - what am I missing?
> 
> ![image](https://user-images.githubusercontent.com/122941077/213428586-5cecabae-a5f8-4c14-ae2a-aff718c67f88.png)

expand it
