### ISSUE TITLE
Custom Teleport setting : Delete Checked not work

### ISSUE THREAD

**Issue by WHOIAM121** [Akebi-Private/Akebi-Issue-Tracker#142]
i tried to delete checked json files with "Del Checked" function but they are not deleted

**Comment by RyujinZX** [comment]
Please record a video

**Comment by WHOIAM121** [comment]
https://youtu.be/h0UXnyQqb1M

**Comment by RyujinZX** [comment]
Okay thanks, I'll fix it

**Comment by RyujinZX** [comment]
fixed
