### ISSUE TITLE
`Free Camera`: Co-op Friend Invisible (Free Camera Category)

### ISSUE THREAD

**Issue by SylverOmar** [Akebi-Private/Akebi-Issue-Tracker#146]
co-op friend invisible, the 1st time happened to me and it's the 1st time I enabled "Make character invisible", under "free camera" section, to try it then disabled it again, and this before going co-op, so I think it's related to it.
- they're invisible in our both worlds
- I tried disabling all other cheats and even create a new cheat profile but still didn't solve the problem
- tried the game without akebi no problem
- checked cfg.json it's false
- tried even to delete it from cfg.json but the game was stuck on black screen after "enter" ^^' (glad I did a backup)
- PS: Free camera option still Broken, crashes the game after disabling it

![Screenshot (920)](https://user-images.githubusercontent.com/101500889/213875908-03ac2e92-7c40-4d91-a0a6-fb2fa29c0f61.png)

**Comment by mrjoshuatee** [comment]
I wanted to add another notee to this issue... Many enemies can't detect your friend either when in coop. They would sit there and attack a fatui blade guy or treasure hoarders and they wouldnt even retaliate. 

Very strange that this bug also affects the enemies ability to detect your friend in Coop

**Comment by FaasHinRah** [comment]
Another part of this is, that your own abilities don't detect teammates. Best example would be Yaoyao, her rabbit doesn't target teammates, some have even claimed to get damaged by the radishes when walking near them.

**Comment by ghost** [comment]
Did you tried it after last update ~20 mins ago.

**Comment by FaasHinRah** [comment]
Didn't know there was an update, going to test it now

**Comment by FaasHinRah** [comment]
Nope, still can't see teammates with the update

**Comment by ghost** [comment]
Did you enable `Free camera`?

**Comment by FaasHinRah** [comment]
No, never used it in the first place, forgot to mention that when reading through this post

**Comment by ghost** [comment]
Okay, also see that, weird.

**Comment by djdoolky76** [comment]
i also use the latest update, and I try to farm talent material in co-op mode and I can't see my co-op teammates even without free camera tho

**Comment by FaasHinRah** [comment]
Oh, I think they just fixed it. There was an update when I relaunched and now I can see my friend normally

**Comment by ghost** [comment]
Yeah, should be fixed now.
