### ISSUE TITLE
`ESP`: Random Stuff as Buried Chest

### ISSUE THREAD

**Issue by SylverOmar** [Akebi-Private/Akebi-Issue-Tracker#148]
Random Stuff detected as Buried Chest

![894868461](https://user-images.githubusercontent.com/101500889/213876509-10433e91-a85b-4f18-8901-b58c457f69b7.png)
![4158469541](https://user-images.githubusercontent.com/101500889/213876527-91e943c1-32f3-4930-9f1f-e73ab6c7bcf9.png)
![641654165841](https://user-images.githubusercontent.com/101500889/213876547-b7634d1c-a723-4c73-af6e-a298d8fc31ae.png)

**Comment by RyujinZX** [comment]
oh need coord or screen map
