### ISSUE TITLE
`ESP`: 2 Time Trial options in ESP (one wrong)

### ISSUE THREAD

**Issue by SylverOmar** [Akebi-Private/Akebi-Issue-Tracker#150]
there are 2 time trial challenge options in ESP:
- 1 under "Featured"
- 1 under "Puzzle"
The 1 under puzzle detects wrong stuff

![98465184](https://user-images.githubusercontent.com/101500889/213877456-3af35d5e-e6f7-426c-9b15-14f1434b4d4a.png)
![Screenshot (926)](https://user-images.githubusercontent.com/101500889/213877549-b857822a-9946-43b5-9df0-71f6cb9871a0.png)

**Comment by ghost** [comment]
Please give locations of the wrong ESP items.
