### ISSUE TITLE
Failed to connect to key

### ISSUE THREAD

**Issue by XcKiller** [Akebi-Private/Akebi-Issue-Tracker#152]
![image](https://user-images.githubusercontent.com/123112616/213880183-063073e1-c5bd-4d3e-bbbb-07886e222736.jpeg)

What is the issue?

**Comment by xwj8868** [comment]
Excuse me, where can I download the latest version for each update?

**Comment by XcKiller** [comment]
In the news section on discord server

**Comment by xwj8868** [comment]
Could you please give me a link?

**Comment by XcKiller** [comment]
This is the discord server : https://discord.gg/akebi


This is the latest version of akebi : 

https://anonfiles.com/38MbeeT7y4/AkebiPrivate_zip


http://cdn.akebi.dev/AkebiPrivate-hotfix.zip

Chose one of them.

**Comment by xwj8868** [comment]
Thank you very much. I would also like to ask why I can't open the website address of the updated link you sent.
