### ISSUE TITLE
`ESP`: Completed time trial challenge shown in esp

### ISSUE THREAD

**Issue by Arvesso** [Akebi-Private/Akebi-Issue-Tracker#154]
![sn](https://user-images.githubusercontent.com/109855015/213886278-5d1d391a-4526-4439-b1cb-bf238c39a692.png)

**Comment by dthrcrpz** [comment]
I solved it by checking Time Trial Challenge under Puzzle instead of Featured
![image](https://user-images.githubusercontent.com/25061004/213899227-755b692a-7b3d-4871-a536-01b06614c5e1.png)

**Comment by ghost** [comment]
Duplicate #147
