### ISSUE TITLE
I bought the key. Where can I download to the latest version? After each update, the software cannot be automatically updated, and there is no link to download the latest version.

### ISSUE THREAD

**Issue by xwj8868** [Akebi-Private/Akebi-Issue-Tracker#156]
I bought the key. Where can I download to the latest version? After each update, the software cannot be automatically updated, and there is no link to download the latest version.

**Comment by RyujinZX** [comment]
![image](https://user-images.githubusercontent.com/101382869/213887871-37c5e84b-8f31-491f-9fb0-5ade96976534.png)

**Comment by RyujinZX** [comment]
discord - news, last links
