### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by XcKiller** [Akebi-Private/Akebi-Issue-Tracker#157]
It would be better to adjust the slider on the auto loot range or any other cheat to be like the free version which you can put the exact value you want.

**Comment by RyujinZX** [comment]
right click 
![image](https://user-images.githubusercontent.com/101382869/213889676-6d166040-73e1-4775-a3f3-8d636c4f4cd0.png)

**Comment by FaasHinRah** [comment]
right click it

**Comment by ghost** [comment]
`Shift + LMB` also
