### ISSUE TITLE
`Vacuum Loot`: Sunsettia & Apples can't be Claimed with "Vacuum Loot"

### ISSUE THREAD

**Issue by SylverOmar** [Akebi-Private/Akebi-Issue-Tracker#169]
When ticking "Apple" and "Sunsettia" under "Vacuum Loot" you can't take them either manually or with "Auto Loot", they're stuck there even if you click on them to claim nothing happens, just following you.
(Sometimes they can be claimed maybe when you get close enough to them)
(I'm setting 100 on Radius)

![dshgdbndg](https://user-images.githubusercontent.com/101500889/213908007-b39f6e6a-9422-42cc-82fc-c7bb4eb12537.png)

**Comment by ghost** [comment]
Firstly, it's dangerous to use Vacuum Loot with big range, and yeah, with range `100` some far items can't be collected due to server check.
