### ISSUE TITLE
Feature request: can you add a lifetime key?

### ISSUE THREAD

**Issue by Kruon** [Akebi-Private/Akebi-Issue-Tracker#173]
i just want to suggest a lifetime key for like around 100$ because I think it will be a normal price for a lifetime key if the price for a month is 20$. just a lifetime key is more convenient and better than spending $20 every month

**Comment by djdoolky76** [comment]
impossible

**Comment by ghost** [comment]
For me lifetime, mean support until the game exists. But, due to genshin protection, that improve with almost each version, we can't surely say that do support for the long time. So, for now only one month solution exists.
