### ISSUE TITLE
[BUG] Fishing is not working

### ISSUE THREAD

**Issue by zhanggyarcher** [Akebi-Private/Akebi-Issue-Tracker#175]
Hi,

When I try to use the fishing feature, it cannot catch the fish. The fish keeps getting scared and run away. Could someone fix this?
If you need more information, I am glad to help. Thank you so much!

**Comment by kumamowa** [comment]
Подтверждаю, у меня такая же фигня, хотел про неё написать. Рыбалка работает криво, тестил с включённой рыбалкой, выключив всё остальное - та же ситуация

**Comment by Faithy123** [comment]
Тут, наверно, стоит подчеркнуть, что не работает именно функция Recast rod. После первой поимки рыбы - прочая действительно не ловится и пугается, или багуется вообще. Но первая рыба ловится нормально, сама рыбалка работает, если вручную перезакидывать удочку

**Comment by zhanggyarcher** [comment]
> Тут, наверно, стоит подчеркнуть, что не работает именно функция Recast rod. После первой поимки рыбы - прочая действительно не ловится и пугается, или багуется вообще. Но первая рыба ловится нормально, сама рыбалка работает, если вручную перезакидывать удочку

Same for me. I can catch the first fish smoothly using the cheat, but starting from the second fish, I can never catch it, no matter if I restart the game, change the river, wait for the second real day, etc.

**Comment by zhanggyarcher** [comment]
May I ask when will this be fixed?

**Comment by zhanggyarcher** [comment]
[Video for fishing bug](https://drive.google.com/file/d/1Fe2OS6oIe4BH6-mWpbMgd7IrhSB23zuH/view?usp=share_link) 

I have attached a video here

**Comment by ghost** [comment]
Duplicate of #102. This information linked to it.
