### ISSUE TITLE
Attack Speed - Not working after latest Update

### ISSUE THREAD

**Issue by TozoPozo** [Akebi-Private/Akebi-Issue-Tracker#177]
Attack Speed doesn't work after the latest update.

**Comment by zhanggyarcher** [comment]
agree

**Comment by RyujinZX** [comment]
enable attack modifier

**Comment by TozoPozo** [comment]
Oh,  It works after enabling!  Previous version it works without enabling that.  I thought "Enable attack modifier" was for Multi-Hit features.  But I guess that's not the case now.  Thank You!
