### ISSUE TITLE
Некорректно отображаются новые камни (обелиски) в пустыне в ESP

### ISSUE THREAD

**Issue by kumamowa** [Akebi-Private/Akebi-Issue-Tracker#179]
В список камней с символами в ESP внесены не все камни. Изначально камни на скрине вообще не отображались через ESP, например, пока на хотя бы одном из них не появился символ, внесённый в ESP.
![image](https://user-images.githubusercontent.com/78809470/213932447-38eb157b-45c0-4d1e-876c-1e1a6705585d.png)
![image](https://user-images.githubusercontent.com/78809470/213932463-ef9cf2e0-6354-4df2-95a6-abf694eb2344.png)

**Comment by RyujinZX** [comment]
ok i check

**Comment by RyujinZX** [comment]
This is normal behavior because the stone shown is the main one for this challange
