### ISSUE TITLE
`UI`: The game freeze when i press F1

### ISSUE THREAD

**Issue by Yakonche** [Akebi-Private/Akebi-Issue-Tracker#18]
I can't access to the menu because it freeze each time i press on the menu key
I'm on W11, play on 2160p@60 with xbox controller

**Comment by ghost** [comment]
Did you still have such issue after latest update?

**Comment by Yakonche** [comment]
Yeah I still have the problem, F1 menu freeze some seconds after opened him
(game freeze too) so I can't edit cheats I want

PS : 5€/month would be good, not more
