### ISSUE TITLE
Auto-pickup not working starting from 2023/01/23 update

### ISSUE THREAD

**Issue by zhanggyarcher** [Akebi-Private/Akebi-Issue-Tracker#185]
Hi,
I noticed that on Jan23 15:50 GMT+8 we had a hot fix of our cheat.

After I have updated this cheat, I noticed that our auto-pickup feature started to be not working properly. Originally, when I turn on this feature, it can automatically pickup without pressing "F". Now I have to manually pressing "F" to pickup. In this attached video, you can hear I have to manually press"F" on my keyboard.

Could someone fix this? Thanks!

**Comment by zhanggyarcher** [comment]
https://user-images.githubusercontent.com/36641890/214004519-b223fea2-f8b6-4210-bb87-e30c61dee24d.MOV

**Comment by zhanggyarcher** [comment]
Also auto loot is not working for this version

**Comment by WHOIAM121** [comment]
I don't know what's wrong with your Auto Loot but mine is fine, my Auto Loot works fine

**Comment by zhanggyarcher** [comment]
> I don't know what's wrong with your Auto Loot but mine is fine, my Auto Loot works fine

I don't know actually, I didn't change anything. It was working fine yesterday and in all previous versions

**Comment by zhanggyarcher** [comment]
resolved
