### ISSUE TITLE
`Performance`: Random Stuttering During Gameplay

### ISSUE THREAD

**Issue by jimmyazrael** [Akebi-Private/Akebi-Issue-Tracker#186]
Experiencing ranmdom stuttering during gameplay. Game/video will pause for ~0.5 secs occasionally when using the cheat.

Attching my settings for reference (I used similar settings in previous versoins and never experienced such issue).
[cfg.json.txt](https://github.com/Akebi-Private/Akebi-Issue-Tracker/files/10480445/cfg.json.txt)

**Comment by GC-Ruth** [comment]
I suggest you get a better computer

**Comment by jimmyazrael** [comment]
> I suggest you get a better computer

I hope you're not representing the dev/support with such reply of ignorance and arrogance. How about thinking this sentence through before commenting: 
`I used similar settings in previous versoins and never experienced such issue`?

Besides, here's my PC specs:

12-Core AMD Ryzen 9 3900XT, 4276 MHz
Gigabyte X570 Aorus Master
G Skill TridentZ F4-3600C16-16GTZNC 16 GB DDR4-3600 DDR4 SDRAM  (16-19-19-39 @ 1801 MHz) x 2
ASUS Strix NVIDIA GeForce RTX 3090
Sabrent Rocket 4.0 2TB
Corsair AX1600i 1600W

**Comment by zhanggyarcher** [comment]
Same for me. In addition to that, I often face the problem of flash quit or restart the computer. I had similiar config with @jimmyazrael 
i9-11900k
ROG M12E
RTX-3090
Samsung 990 Pro ssd
G skill ddr4 4000C18

**Comment by countstars-xing** [comment]
Me too. My PC configuration is enough

**Comment by Redax88** [comment]
I do find this random stutter/micro freezing. In my head i just assume it has something to do with license server.
