### ISSUE TITLE
Автоматическое открытие сундуков.

### ISSUE THREAD

**Issue by Frostorik** [Akebi-Private/Akebi-Issue-Tracker#188]
Не срабатывает автоматическое открытие сундуков в штормовых заслонах.
![image](https://user-images.githubusercontent.com/116587935/214116107-11c3e859-f33d-4fdf-87a9-5af3f1f93bf5.png)

**Comment by kumamowa** [comment]
Ноуклипом подпрыгни немного и упади вниз, это механика игры, сундук открывается только если залезть в шторм сверху
