### ISSUE TITLE
After switching to Chinese language, the interface displays a bunch of question marks, and ESP has no effect on CN

### ISSUE THREAD

**Issue by a1047707793a** [Akebi-Private/Akebi-Issue-Tracker#19]
![image](https://user-images.githubusercontent.com/123014254/213265930-4c37cace-920b-41a4-9b0a-7fc9b2f6e31d.png)

**Comment by Taiga74164** [comment]
fixed next update
![image](https://user-images.githubusercontent.com/67109235/213361072-f2d5339b-972a-4b4b-b017-925e0d101c05.png)
