### ISSUE TITLE
`God Mode` sometimes not working

### ISSUE THREAD

**Issue by SylverOmar** [Akebi-Private/Akebi-Issue-Tracker#192]
sometimes the character takes damage with azdaha while god mode is activate (Unconditional God Mode or Conditional both) and if I remember well other bosses too

this pic is unconditional god mode should take no damage at all (hp was 100%):
![Screenshot (947)](https://user-images.githubusercontent.com/101500889/214344030-77ee3cbe-2ee3-45b8-a3b7-0ef1ee3eb0f0.png)

**Comment by yorik100** [comment]
Not all types of damage is covered by conditional Godmode, you have to put missing attack rate to 100% to fix that which ignores the minimum HP% set above

**Comment by SylverOmar** [comment]
That's normal (unconditional) god mode on the picture
