### ISSUE TITLE
`Common`: Game Freezes or Crashes Randomly 

### ISSUE THREAD

**Issue by SylverOmar** [Akebi-Private/Akebi-Issue-Tracker#195]
the game bugs and freezes for a couple of seconds, or crashes altogether and closes randomly

**Comment by zhanggyarcher** [comment]
same issue

**Comment by djdoolky76** [comment]
sometimes gets freeze for a couple of secs but no crash

**Comment by RyujinZX** [comment]
Do you have a stable internet connection? Is the ping not high?

**Comment by SylverOmar** [comment]
Yeah sometimes internet does it, but I used akebi for about 5 months I noticed it's not normal
and ig internet doesn't crash and close the game

**Comment by RyujinZX** [comment]
> Yeah sometimes internet does it, but I used akebi for about 5 months I noticed it's not normal and ig internet doesn't crash and close the game

The failure could be because our server loses communication with you, which is why I asked about the quality of your connection.
