### ISSUE TITLE
BUG time challenge follow me

### ISSUE THREAD

**Issue by tayhm0817** [Akebi-Private/Akebi-Issue-Tracker#203]
![image](https://user-images.githubusercontent.com/104625131/214733888-0dad1cdd-da1f-466f-8db4-babcef11ce12.png)

**Comment by tayhm0817** [comment]
![image](https://user-images.githubusercontent.com/104625131/214733954-7f4a22fd-f8dc-4af3-ba8a-3b92b7141f7c.png)
this is what i use

**Comment by MongMikng** [comment]
same

**Comment by Redax88** [comment]
same
![image](https://user-images.githubusercontent.com/112399500/214767186-03aab24e-6fc9-4b65-b1db-6c08724b3ac1.png)

**Comment by RyujinZX** [comment]
it looks like an auto challenge, I'll fix it guys

**Comment by trasser** [comment]
same. Disable auto challenge work

**Comment by countstars-xing** [comment]
me too.
