### ISSUE TITLE
DEBUG: Empty gadgets

### ISSUE THREAD

**Issue by trasser** [Akebi-Private/Akebi-Issue-Tracker#204]
Time trial challenge on radar bunt in fact trash

screen 

{ x = 2270.6418, y = 233.54039, z = -893.2632 }
{ x = -10.853516, y = 233.54039, z = -25.578003 }
{ x = 893.2632, y = 2
![Genshin Impact 26 01 2023 10_31_10](https://user-images.githubusercontent.com/18208920/214780735-c212d8b4-a14b-41c2-9359-8bd5c075716d.png)
270.6418 }
{ x = 0, y = 1, z = 0 }

**Comment by ANT4XRES** [comment]
Fixed in new akebi update, dont use Debug emtpy gadget, Use time trial from Featured Section

**Comment by trasser** [comment]
> Fixed in new akebi update, dont use Debug emtpy gadget, Use time trial from Featured Section

Lol, time trial monument now vacuum to me and follow
