### ISSUE TITLE
`God mode` not working in sumeru region (withering)

### ISSUE THREAD

**Issue by 180107113** [Akebi-Private/Akebi-Issue-Tracker#206]
not only in this quest but in the whole region on the screenshot it is not working. video attached.
![Новый точечный рисунок (2)](https://user-images.githubusercontent.com/55224038/214793425-bcece2cc-5390-4576-8539-13e92f1abe77.jpg)

https://youtu.be/gTkyRRXyaxY

**Comment by TAHKYCb** [comment]
GODMOD не работает при прохождении квеста Аранар (Питомник утраченных грез "Во имя детей прошлого")
У меня так же (
{ x = -681.0899, y = 117.16875, z = 3795.582 }
