### ISSUE TITLE
Feature Request : can use it with 3dmigoto

### ISSUE THREAD

**Issue by MrsAya** [Akebi-Private/Akebi-Issue-Tracker#209]
i like to mod some chara with akebi to play with it so. its just a request i hope it can be like that.
Thanks #

**Comment by WHOIAM121** [comment]
you can easily use 3dmigoto with akebi at the same time, first you open 3dmigoto, when 3dmigoto is ready then open akebi, simple bro

**Comment by MrsAya** [comment]
Thanks
