### ISSUE TITLE
[BUG] Akebi fails to request license key after game launch

### ISSUE THREAD

**Issue by lagopodous** [Akebi-Private/Akebi-Issue-Tracker#211]
Followed FAQ but so far nothing has helped. Acrepi ran fine (even with defender and afterburner). Disabling those didn't help now. Video shows the issue perfectly. The issue is same if using pure executable or launcher.

-analog_inject method doesn't work at all, the empty cmd shows up but just fails to launch the game and disappears, leaving suspended Genshin client in the processes tab.

https://user-images.githubusercontent.com/115150572/215074320-99106533-7fd6-4849-8ff4-afd188421e86.mp4

**Comment by lagopodous** [comment]
I still can't use Akebi. I guess I should just refund the key then as it looks like no one is interested to help me?

**Comment by ghost** [comment]
Seems like problem with your internet connection, try to use VPN. Actually, I think you already refunded it, so I close it.

**Comment by lagopodous** [comment]
Actually I haven't refunded it yet. Is there a way around without VPN? I live in Finland if it's any help. Sent you a dm in discord
