### ISSUE TITLE
[BUG] Infinite stamina (move Sync Packet Replacment) not work for ayaka and Mona

### ISSUE THREAD

**Issue by WHOIAM121** [Akebi-Private/Akebi-Issue-Tracker#212]
Stamina always runs out when Ayaka or Mona runs
please Fix this

**Comment by romanocry** [comment]
hi, 
without changing anything in my config, Stamina is not working for all character... 
is anyone have same issue ?

**Comment by WHOIAM121** [comment]
mine works fine for all characters except ayaka and mona, maybe i can help you if you show screenshots of what cheats you activated

**Comment by ghost** [comment]
Duplicate of #207 #120
