### ISSUE TITLE
`Feature Request`: Add information about manual TP in `Info window`

### ISSUE THREAD

**Issue by TAHKYCb** [Akebi-Private/Akebi-Issue-Tracker#220]
Добавить поках названия Какстом телепорта при ручной телепортации, так же как при авто.
При авто показывает название точки, если выключить то расширение пропадает.

`https://imgur.com/a/bQvx4qN`

**Comment by kumamowa** [comment]
> Добавить поках названия Какстом телепорта при ручной телепортации, так же как при авто. При авто показывает название точки, если выключить то расширение пропадает.
> 
> `https://imgur.com/a/bQvx4qN`

![image](https://user-images.githubusercontent.com/78809470/215338112-59934be6-95c9-4416-8bc4-350f1aa771e4.png)
