### ISSUE TITLE
Cannot be openedm, Tips:[Error] ManualMap: Failed to initialize static TLS for image. Error: 0

### ISSUE THREAD

**Issue by jike87** [Akebi-Private/Akebi-Issue-Tracker#223]
Cannot be openedm, Tips:[Error] ManualMap: Failed to initialize static TLS for image. Error: 0
![image](https://user-images.githubusercontent.com/124066058/215795731-18d98e30-800a-4389-b3f2-f658e1178e47.png)

**Comment by Taiga74164** [comment]
https://user-images.githubusercontent.com/67109235/215915239-0e0ed550-1413-4316-89d8-dc483c80de0e.mp4
