### ISSUE TITLE
BUG ESP

### ISSUE THREAD

**Issue by fedukme** [Akebi-Private/Akebi-Issue-Tracker#225]
After passing the riddle, for some reason, these esp do not want to disappear, although they disappeared on the free akebi
![IMG_20230201_145842_032](https://user-images.githubusercontent.com/119656423/216036583-5ca97981-8550-435d-b705-c5e3f32b50ce.png)

**Comment by RyujinZX** [comment]
> After passing the riddle, for some reason, these esp do not want to disappear, although they disappeared on the free akebi ![IMG_20230201_145842_032](https://user-images.githubusercontent.com/119656423/216036583-5ca97981-8550-435d-b705-c5e3f32b50ce.png)

Disable empty gadget in esp..
