### ISSUE TITLE
`Protection`: Abnormal data message

### ISSUE THREAD

**Issue by xwj8868** [Akebi-Private/Akebi-Issue-Tracker#237]
Why I have updated the latest version but the data is still abnormal?

**Comment by ghost** [comment]
Still the same?

**Comment by xwj8868** [comment]
Yes, the data exception message is still displayed

**Comment by xwj8868** [comment]
> 还是一样吗？

Yes, the data exception message is still displayed

**Comment by ghost** [comment]
Can you dm me in discord? Callow#1429

**Comment by ghost** [comment]
Issue was with extra `.dll` or `.exe` files in game directory, moving this files fixed error.
