### ISSUE TITLE
`Translation`: The Chinese translation of sand grease pupa is 沙脂蛹

### ISSUE THREAD

**Issue by layla020** [Akebi-Private/Akebi-Issue-Tracker#239]
ESP  The Chinese translation of sand grease pupa is 沙脂蛹 
![翻译沙脂蛹](https://user-images.githubusercontent.com/111977536/218196926-aa85d2e6-5d0a-4c5b-ba61-7fb9cfa658de.png)

**Comment by ghost** [comment]
We will introduce way to add custom translations soon. So then it can fixed.
