### ISSUE TITLE
`Bug collection`: Collection from `yorik100`

### ISSUE THREAD

**Issue by yorik100** [Akebi-Private/Akebi-Issue-Tracker#24]
Global :
 - Unable to change the values of sliders by shift clicking (to put a precise value)
 - If it finishes injection before you enter your world, you're softlocked and you can't click anywhere on the screen to join your world
 - When console pops up and injection starts, it kicks you out of the game if you're in fullscreen (console should start before the game itself to avoid that)

Player :
 - ~~Attack speed is enabled even if you disable attack effects~~
 - ~~Auto fishing does not restart fishing~~
 - Make a workaround to avoid having to change map to disable custom effects if possible
 - There should be crash/true damage in element selector
 - There should be an option in infinite stamina to only not send stamina packets when stamina is empty
 - Move sync packet replacement infinite stamina doesn't work with charged attack stamina
 - Missing no fall (full/soft)
 - Conditional Godmode does not work properly, if set a minimum health 100%, you're still able to get damaged by cold damage
 - Missing rate in Godmode does not have an option to choose under which % HP it should activate itself
 - (Separate skill and burst cooldown)

World :
 - Unpressing the auto talk button does not unspeed the game anymore
 - Auto destroy doesn't work with Sakura Bloom and ice stuff that can be melted in Dragonspine Mountains
 - AutoCook still crashing with Fast Proficiency

ESP :
 - ~~Time Trial that is already done is still getting tracked by ESP~~
 - Seelie ESP makes Seelie ESP boxes teleport to yourself for a split second then come back to original place if Auto Seelie is enabled

Visuals :
 - Freecam gets activated with the hotkey when chatting in the chat
 - Custom FoV overrides Freecam FoV (it shouldn't)
 - Tracer object icons missing (was in 3.3 version)
 - In interactive map, "White iron chunk" has question marks instead of spaces, many object names have the same issues
 - The info window changes its size constantly which is annoying (constantly as in every single step due to numbers not having the same size)
 - Time Trial not properly detected by ESP and detecting random stuff as Time Trial (fairies, cryo cube, cryo plant, ...)

**Comment by OYlllan** [comment]
Hello, sir. I want to know how to unbind. I want to use it on my other computer
