### ISSUE TITLE
`CustomTeleports`: `Reload` hotkey in teleports not work properly

### ISSUE THREAD

**Issue by phenacemide** [Akebi-Private/Akebi-Issue-Tracker#246]
Before update if i press `Reload` hotkey - then cheat will:
1. Reload teleport points
2. Select all teleport points
3. Start auto teleport from first teleport point

But now 2nd and 3rd points not working

**Comment by ghost** [comment]
Sorry for giving long waiting for answer, but now are you sure that it's not working the same way. Or problem already fixed?

**Comment by phenacemide** [comment]
Hi, sorry for the long reply too. No, problem isnt fixed. And yep im sure it worked differently.
Earlier, when you pressed reload hotkey - cheat reloads teleports, chooses all tps and starts autoteleport from first tp.

Btw now if you have tps.json in teleport folder so then cheat starts automated autoteleport if you have options like screen below (previously it didnt work as it works now.)
![изображение](https://user-images.githubusercontent.com/116737958/227965906-f2e33430-4d9b-46aa-a7ea-30afc5ca2d55.png)
