### ISSUE TITLE
`Auto Seelie` not working in new version.

### ISSUE THREAD

**Issue by ufufufu** [Akebi-Private/Akebi-Issue-Tracker#249]
This bug report is to report that the auto seelie doesn't seem to be working in the latest version.

The video [here](https://mega.nz/file/QgwByKob#JR5Sgq2omNDk1koW72kHkDUNsfhJN5JynhzF9tVyd3s) (valid 48 hours) should demonstrate how the auto seelie feature not working as it should. I expect the seelie to fly to its destination without any more intervention.

**Comment by ghost** [comment]
Is fixed already?

**Comment by ufufufu** [comment]
Doesn't seem so.
