### ISSUE TITLE
`Hide UI` seems irreversible

### ISSUE THREAD

**Issue by long385552** [Akebi-Private/Akebi-Issue-Tracker#26]

**Comment by long385552** [comment]
![image](https://user-images.githubusercontent.com/55587343/213269481-c30106b8-6797-4bcc-9b39-ea6662b44154.png)

**Comment by long385552** [comment]
Therefore, the Akebi UI is invisible , I can't do anything.

**Comment by LookMomihaveaUsername** [comment]
You can turn it of and restart the Game. That's the ony fix i know of yet. Had the same Problem.
