### ISSUE TITLE
`Help wanted`: Failed to close mhyprot2 handle. Report this Issue and describe it.

### ISSUE THREAD

**Issue by KokHji** [Akebi-Private/Akebi-Issue-Tracker#264]
I using it this morning was normal, 
and not working after work
Have run as admin, re-download, run as new  program, restart PC. Still same issues

**Comment by KokHji** [comment]
![2023-03-13_194900](https://user-images.githubusercontent.com/127760246/224724508-0a154624-f3dc-4125-b0f6-e0b071616ffb.jpg)

**Comment by KokHji** [comment]
![2023-03-13_194900](https://user-images.githubusercontent.com/127760246/224725080-5ff5934d-f51a-4485-8dec-a545a728f5a0.jpg)

**Comment by KokHji** [comment]
Game start normally, jut cannot bypass the mhyport2

**Comment by ghost** [comment]
Did you deleted `mhypbase.dll`?

**Comment by KokHji** [comment]
Haven't touch anything in the game files
and checked both mhypbase.dll and mhyprot3.Sys still there

**Comment by ghost** [comment]
Check #267 267
