### ISSUE TITLE
`Config`: повторный ввод ключа при смене конфига

### ISSUE THREAD

**Issue by monkrel** [Akebi-Private/Akebi-Issue-Tracker#272]
Проблема: инжектор просит ключ для каждого нового конфига.

Как воспроизвести:

1. Создать новый конфиг в игре
2. Загрузить его
3. Выйти из игры
4. Запустить инжектор снова

Пример решения:  вынести сохранение ключа авторизации из-под конфига

**Comment by G3tHx** [comment]
Благодарим Вас за фидбек! Обязательно разберёмся с данной проблемой в будущем. Приятной игры с AKEBI!
