### ISSUE TITLE
Attack Speed Function gone 

### ISSUE THREAD

**Issue by OneAutumnLeafXiao** [Akebi-Private/Akebi-Issue-Tracker#28]

**Comment by yorik100** [comment]
It isn't gone, to enable it, enable multi animation, enable attack speed and then disable multi animation

**Comment by OneAutumnLeafXiao** [comment]
I see! Thank you. a little bit hard to figure out but thanks for letting me know

**Comment by yorik100** [comment]
> I see! Thank you. a little bit hard to figure out but thanks for letting me know

Pretty sure it's an oversight
