### ISSUE TITLE
Rock piles destruction (in auto puzzles) not working on 3.6 rocks, BUT it works as Doaads destruction (Bug)

### ISSUE THREAD

**Issue by immissaISG** [Akebi-Private/Akebi-Issue-Tracker#280]
For example:

{ x = 656.33405, y = 331.40997, z = 6146.7026 }
![image](https://user-images.githubusercontent.com/123281150/231749612-b727ff9c-435a-440b-8604-f7aebbe08019.png)

**Comment by Frostorik** [comment]
https://cdn.discordapp.com/attachments/1081547525389029406/1096044443502657546/1212.mp4

**Comment by menleev** [comment]
закрывайте тикет...
