### ISSUE TITLE
Destroy shield for Oceanid no work v.v

### ISSUE THREAD

**Issue by takeshi7502** [Akebi-Private/Akebi-Issue-Tracker#281]
Please fix it

**Comment by RyujinZX** [comment]
Oceanid, has no shields. Accordingly, I decline this request

**Comment by takeshi7502** [comment]
I don't think so, Oceanid has a shield that prevents it from being directly
damaged by players, [CyperCore] another hack I know that can break this
shield to help kill bosses faster.

Vào 4:05, Th 3, 18 thg 4, 2023 RyujinZX ***@***.***> đã viết:
