### ISSUE TITLE
`Feature request`: Add support unicode utf8 in Akebi

### ISSUE THREAD

**Issue by takeshi7502** [Akebi-Private/Akebi-Issue-Tracker#283]
Please support unicode utf8 for akebi
I am an akebi vietnamese user, please support unicode utf8 on akebi so that i can translate the language into vietnamese, when i write in vietnamese with accents it has a character error.
Please
Please
Please

**Comment by ghost** [comment]
Sorry for long answer, contact me in discord. Callow#1429

**Comment by ghost** [comment]
It's font issue, we need add vietnamese font, for this, so, if you still interested, write discord above.
