### ISSUE TITLE
`Interactive map`: Mini-puzzles dissapeared

### ISSUE THREAD

**Issue by Faithy123** [Akebi-Private/Akebi-Issue-Tracker#285]
![нет мини пазлов](https://user-images.githubusercontent.com/122793073/231828253-9b0c4b07-4f30-4c45-b7ce-ab09ccb32e8a.png)

После обновления в нижнем разломе пропали mini puzzles (мини загадки) с интерактивной карты.

**Comment by ghost** [comment]
Мы берём данные с интерактивки михоё, там это выпилили по каким-то причинам
