### ISSUE TITLE
[Bug] Auto destroy sand pile will make game crash.

### ISSUE THREAD

**Issue by Lincutt** [Akebi-Private/Akebi-Issue-Tracker#289]
Auto destroy sand pile will make game crash
when set ANY custom element in attack effects.

**Comment by RyujinZX** [comment]
> Auto destroy sand pile will make game crash when set ANY custom element in attack effects.

Specify the coordinates where it happens

**Comment by RyujinZX** [comment]
video is desirable, because I can't provoke the problem

**Comment by Lincutt** [comment]
> > Auto destroy sand pile will make game crash when set ANY custom element in attack effects.
> 
> Specify the coordinates where it happens

824.2780, 313.7430, 6140.7012
