### ISSUE TITLE
Hide completed puzzles seems to not work

### ISSUE THREAD

**Issue by zyloxmods** [Akebi-Private/Akebi-Issue-Tracker#29]
![Screenshot 2023-01-18 203343](https://user-images.githubusercontent.com/76428709/213277124-caa7a8bb-50a3-4382-b1e3-fb4ef0bd5815.png)

**Comment by 0xZylox** [comment]
wait wrong image lmao
![Screenshot 2023-01-18 203343](https://user-images.githubusercontent.com/76428709/213277124-caa7a8bb-50a3-4382-b1e3-fb4ef0bd5815.png)

**Comment by yorik100** [comment]
I confirm

**Comment by Arvesso** [comment]
I confirm

**Comment by ghost** [comment]
Duplicate #106
