### ISSUE TITLE
[Bug] The fall speed is too slow when jump on bouncy mushroom.

### ISSUE THREAD

**Issue by Lincutt** [Akebi-Private/Akebi-Issue-Tracker#290]
The fall speed is too slow when jump on bouncy mushroom
when set attack speed multiplier over 1.2 in attack effects.

**Comment by RyujinZX** [comment]
> The fall speed is too slow when jump on bouncy mushroom when set attack speed multiplier over 1.2 in attack effects.

Specify the coordinates where it happens
