### ISSUE TITLE
As a user, I would like to make a suggestion to the author

### ISSUE THREAD

**Issue by Jookemyyy** [Akebi-Private/Akebi-Issue-Tracker#292]
The author can consider adding a feature that allows users to pause the usage time of the software at any time. I believe that most users who purchase this software do not always use it. The author can add a pause time feature, which can greatly reduce the waste of unused time by users after purchasing. Adding a pause time feature can also greatly increase the cost-effectiveness of users, so that new users will also be willing to purchase, I hope the author can consider adding a pause time function at any time!!!

**Comment by isxlan0** [comment]
You can pause once

**Comment by misaka-0x0d** [comment]
暂停已经有了

**Comment by JSPiRiT1337** [comment]
money
