### ISSUE TITLE
Feature request: A new Auto Puzzle is needed

### ISSUE THREAD

**Issue by isxlan0** [Akebi-Private/Akebi-Issue-Tracker#293]
![image](https://user-images.githubusercontent.com/124419906/232205901-4cb46330-4ea7-43b7-ae5f-9e1167ac8dd6.png)
I need automatic puzzles for these things!
Thank you!

**Comment by RyujinZX** [comment]
I can't do that right away, I need to figure out how the sorush system works

**Comment by isxlan0** [comment]
OK, thanks
