### ISSUE TITLE
Launcher issues

### ISSUE THREAD

**Issue by almntsfyf** [Akebi-Private/Akebi-Issue-Tracker#3]
1. Steps
1.1 first way
1.1.1 Start paid cheat from free cheat directory with all configs
1.1.2 Activation code redeemed successful
1.1.3 Game loaded, i played for ~5min
1.1.4 Game freezed and then crushed
1.1.5 Every launch it writes "Injection successful" in cmd, then cdm closes by itself
1.1.6 Game freezes in loading screen and then crushes
1.1.7 Launching paid cheat with _-analog_inject_ thru command line(w/ and w/o adm), Power Shell(w/ and w/o adm), link with command in object, with this argument command lina and game not even launching
1.2 Second way
1.2.1 Start cheat from new clear directory, no redeem requirement
1.2.2 from now on the same result starting from step 1.1.4

2. Working app

3. Game crushing and app not even running(if with argument)

**Comment by almntsfyf** [comment]
Looks like its auth issue, bc now when i launch cheat, main menu loads and then i have completely empty Authentification cmd window
![image](https://user-images.githubusercontent.com/123007944/213259821-8b808899-9400-4399-8dec-5e33a27a02e6.png)

**Comment by almntsfyf** [comment]
Authentification now works, but only on clear setup, i tried move only ESP and Map settings, which is essential features for me, map transfered ok, but EPS settings not completely transfered - only general settings(Enable checkbox and drawing distance), but item settings just clear.

PLS add note that this version not compatible with previous versions.

**Comment by OYlllan** [comment]
![image](https://user-images.githubusercontent.com/122962407/213369760-b649dda0-177d-4921-a7c9-791d9b1f27e9.png)
What should I do

**Comment by OYlllan** [comment]
I don't have the option to enter the card number

**Comment by almntsfyf** [comment]
@OYlllan try this https://github.com/Akebi-Private/Akebi-Issue-Tracker/issues/9#issuecomment-1387513170

**Comment by ghost** [comment]
Check FAQ in discord.
