### ISSUE TITLE
`Feature request`: Contellations Hack

### ISSUE THREAD

**Issue by seventhcreator** [Akebi-Private/Akebi-Issue-Tracker#304]
CottonBuds 3.6 Includes a Contellation Unlock Feature on its Cheat Table. Akebi could enjoy this feature too. Apparently constellations are server sided in a way that you won't unlock them forever. But if the game recognizes it as unlocked, it will buff the character as if you had it.

**Comment by ghost** [comment]
We will not add any game breaking hacks, like contellations hack, money hack, experience hack and etc.
