### ISSUE TITLE
Auto Talk not working

### ISSUE THREAD

**Issue by djdoolky76** [Akebi-Private/Akebi-Issue-Tracker#33]
Not working on NPC's including katherine, after I enable it
![image](https://user-images.githubusercontent.com/30578879/213283175-153cf4cb-cd16-4d56-ae59-adcde1d6f633.png)

**Comment by LookMomihaveaUsername** [comment]
It is. You klick on the Wrench. Select a Hotkey and use it while you Talk.

**Comment by djdoolky76** [comment]
> It is. You klick on the Wrench. Select a Hotkey and use it while you Talk.

Still the same; it's not working

**Comment by LookMomihaveaUsername** [comment]
So. You klicked at the Wrench and setted a Hotkey. And saved it. So when you double check it the hotkey is still there. 
You Pressed the Key while you are in an Interaction with a Quest NPC or Random NPC wich has something to say.

**Comment by trasser** [comment]
Auto talk and auto dialog select dotn work. Only manual by spam hotkey

**Comment by djdoolky76** [comment]
> Auto talk and auto dialog select dotn work. Only manual by spam hotkey

oh that's why. Thanks for noticing

**Comment by LookMomihaveaUsername** [comment]
It works bruh.
I use it and have no problems

**Comment by LookMomihaveaUsername** [comment]
It seems like user Error

**Comment by djdoolky76** [comment]
I figured it out you need to long press a hotkey to make it work which is sucks to me i prefer the old feature

**Comment by ghost** [comment]
Fixed.
