### ISSUE TITLE
Косяки этой версии

### ISSUE THREAD

**Issue by Marussya1201** [Akebi-Private/Akebi-Issue-Tracker#336]
Интерактив новой локи пустой (ладно, фиг с картой), НО долбаный шатер приходится проходить с выключенными автодиалогами (а там болтовни ппц как много); Логово ужаса бури также можно пройти только с выключеными автодиалогами, ну и на заправку - не работает полёт с анимацей 🤬 !

**Comment by monkrel** [comment]
https://github.com/Akebi-Private/Akebi-Issue-Tracker/assets/84017229/0c21c49e-7e77-4e0d-9adf-1550b18633ea
