### ISSUE TITLE
`UI`: Minor UI issues

### ISSUE THREAD

**Issue by RainAfterDark** [Akebi-Private/Akebi-Issue-Tracker#35]
Missing icons in interactive map:
- Dendrogranum
- Clusterleaf of Cultivation
- Primal Obelisk

Sniffer setting names jumbled:
![image](https://user-images.githubusercontent.com/42061128/213288487-3e0469c8-4f3a-4814-b397-d70d3a10404d.png)

**Comment by ghost** [comment]
Dev: shuffled packet sniffer fixed.
