### ISSUE TITLE
Map TP failed

### ISSUE THREAD

**Issue by long385552** [Akebi-Private/Akebi-Issue-Tracker#38]
Map TP will not teleport to desired location. It will teleport to the same place.

**Comment by romanocry** [comment]
Same here, Map TP using Hotkey on map, not teleporting where i need... 
Seems to be a random destination...

**Comment by Waltz1809** [comment]
Same to

**Comment by trasser** [comment]
same

**Comment by ghost** [comment]
Fixed.

**Comment by romanocry** [comment]
i confirm, TP MAP working... but not sure about Quest teleport.
