### ISSUE TITLE
[Bug] ESP fravashi tree no names 

### ISSUE THREAD

**Issue by Thafoxes** [Akebi-Private/Akebi-Issue-Tracker#387]
![image](https://github.com/Akebi-Private/Akebi-Issue-Tracker/assets/43284628/c7f9b2e5-a659-4c5b-8743-d080a5e96388)

**Comment by RyujinZX** [comment]
hmm, it works for me, give me the coordinates of this point, are you sure it is not finished?
![image](https://github.com/Akebi-Private/Akebi-Issue-Tracker/assets/101382869/a594d98f-6f16-444b-8298-a91fea3d856d)

**Comment by Thafoxes** [comment]
![image](https://github.com/Akebi-Private/Akebi-Issue-Tracker/assets/43284628/09dd5fa7-69c2-47d8-91dd-a2fbb57df586)
Completed ones will be hidden
{ x = 686.03864, y = 242.25536, z = 6410.245 }

**Comment by Taiga74164** [comment]
ESP will only show if it's not completed
