### ISSUE TITLE
[Bug] Kill Aura Instant Death Mode doesn't work on the Boss at Khaj-Nisut

### ISSUE THREAD

**Issue by SecPhases** [Akebi-Private/Akebi-Issue-Tracker#396]
refer the title, It guards a golden chest.
Crash Damage Mode works fine on it.
![ebcafa0e2823ed84548288c856a59ac0](https://github.com/Akebi-Private/Akebi-Issue-Tracker/assets/71129766/01389412-12ec-43d4-a1f8-49fbdeb328e0)

**Comment by RyujinZX** [comment]
It's not a bug, instant kill mode from now on won't work where it's not safe.

**Comment by SecPhases** [comment]
> It's not a bug, instant kill mode from now on won't work where it's not safe.

Okay, I see, thank for reply
