### ISSUE TITLE
Crash report

### ISSUE THREAD

**Issue by Azigann** [Akebi-Private/Akebi-Issue-Tracker#40]
![Screenshot_7](https://user-images.githubusercontent.com/46268031/213297679-772a547a-c3d8-42d2-9898-317005b63da3.png)

Console message before crash

**Comment by anhviet26** [comment]
![image](https://user-images.githubusercontent.com/114416480/213299709-2f06f867-8a0e-485b-a12e-9f82f765bc06.png)
I can't boot up

**Comment by ghost** [comment]
Fixed
