### ISSUE TITLE
`Input`: Mouse not moving when press F1

### ISSUE THREAD

**Issue by romanocry** [Akebi-Private/Akebi-Issue-Tracker#41]
Hi,
I use the pay cheat. First time, launch is ok, but don't have time to test
I close the game
Now, i relaunch the game, via akebi Launcher, game launch well, F1 to see UI ok, but mouse not working.
I can't move itunter the cheat UI
F1 still works, and when i close the UI, game still workling well....

what can i do ?

**Comment by yorik100** [comment]
"Sometimes on the title screen, when the game asks you to click to enter the world, it just does not work at all and you can't click on any icons neither forcing you to restart the game" Seems like the issue

**Comment by romanocry** [comment]
Not my issue. Game is launch good.. not block on title screen.
It's in game.

**Comment by FaasHinRah** [comment]
Press F1 again to close it and re-open it again. It happens because when you load into the world, the game locks your mouse to the middle of the screen. Closing and opening the cheat again will fix it.

**Comment by romanocry** [comment]
Not working. Already test.
I also test with only keyboard/mouse (no contrôler) same issue.
Sometimes it's Work... Sometimes not...

Le jeu. 19 janv. 2023 à 06:51, FaasHinRah ***@***.***> a
écrit :

**Comment by ghost** [comment]
Did you have some additional software for mouse?

**Comment by romanocry** [comment]
No third party software at all.
just Win11 driver. 
i have to press F1 multiple time to have , sometime, the possibility to move the cursor.
