### ISSUE TITLE
Game Crashes when exiting domain

### ISSUE THREAD

**Issue by loganeric04** [Akebi-Private/Akebi-Issue-Tracker#42]
Game crashes consistently when I exit the Momiji Dyed Court domain Idk if its just for that domain or for any others or if its just a problem on my side.

**Comment by trasser** [comment]
same

**Comment by trasser** [comment]
Confirm. Is a big problem

**Comment by Taiga74164** [comment]
can you give the features you have enabled..

**Comment by trasser** [comment]
> can you give the features you have enabled..

turn off ESP remove bug.

**Comment by ghost** [comment]
Fixed
