### ISSUE TITLE
HWID Bot & DLL Injection

### ISSUE THREAD

**Issue by xendak** [Akebi-Private/Akebi-Issue-Tracker#44]
I linked my acc to my work computer because I was working from home while traveling and now that I'm back home and wanted to start this thing... welp

![image](https://user-images.githubusercontent.com/108767275/213319432-8e13768a-9c87-4779-8f46-a35cc36b6a19.png)

bot is nowhere to be found, or at least instructions aren't anywhere either..

DLL injection feature is also missing, idk if its intended or not, but kinda sux cuz its annoying to run 3dmigoto without it

**Comment by ghost** [comment]
Should be fine now.
