### ISSUE TITLE
Error to open Akebi

### ISSUE THREAD

**Issue by carlinhossmf** [Akebi-Private/Akebi-Issue-Tracker#49]
Reason: HWID Doesn't match. Use our discord bot to reset it.

![gens](https://user-images.githubusercontent.com/48539268/213341406-e76b50c5-8bbb-4f27-abe8-eb62af6b3b0f.png)

**Comment by LookMomihaveaUsername** [comment]
1. Create a shortcut.
2. Open the shortcut properties
3. In the object field enter "-analog_inject" after GenshinImpact.exe
4. Run via the shortcut.

**Comment by ghost** [comment]
Should be fine now.
