### ISSUE TITLE
Auto Talk Not Working

### ISSUE THREAD

**Issue by loganeric04** [Akebi-Private/Akebi-Issue-Tracker#5]
All of the auto talk features do not seem to be working.

**Comment by kaozaza2** [comment]
Same

**Comment by Aodaah** [comment]
get a keybind for auto talk option and then spam it, probably not intended to work this way but it's a solution until they fix it imo

**Comment by yorik100** [comment]
Hold the auto talk key

**Comment by flyhighup** [comment]
u have to hold it to get the effect

**Comment by flyhighup** [comment]
and I hate it

**Comment by ghost** [comment]
fixed
