### ISSUE TITLE
ESP Setting Resetting

### ISSUE THREAD

**Issue by flyhighup** [Akebi-Private/Akebi-Issue-Tracker#50]
I always have this issue where my ESP selection got resetted everytime I'm log back in to the game

**Comment by motcainit** [comment]
same  problem

**Comment by MongMikng** [comment]
same problem

**Comment by trasser** [comment]
same

**Comment by trasser** [comment]
The same thing. At the same time, if you select a group, it is written to the configuration. Forever. And any changes are not saved (disabling items one by one, changing colors, etc.)

**Comment by ghost** [comment]
Duplicate #101
