### ISSUE TITLE
Game crushing upon completing domain

### ISSUE THREAD

**Issue by almntsfyf** [Akebi-Private/Akebi-Issue-Tracker#55]
I went into Spire of Solitary Enlightenment, completed it, and after that I have to chose leave or try another, both options leads to instant crush, even no freez, game and console just closes.

What i used:
1. AutoDestroy(ores only, 5 meters)
2. AutoLoot(AutoPickup, 5 meters, 400ms delay, 225 delay fluctuation)
3. ESP(200 meters range, only collectables and resources, no enemy)
4. Interactive map
5. SkipEnhanceAnimation(ShowLevelUp)

**Comment by ghost** [comment]
What injection you used? Standard or analog?

**Comment by almntsfyf** [comment]
Standart one

EDIT: tried to launch cheat with -analog_inject from this [solution](https://github.com/Akebi-Private/Akebi-Issue-Tracker/issues/9#issuecomment-1387513170), console started, did nothing for 3 or 4 seconds and then closed itself, game didn't launched, completely nothing happened.

**Comment by trasser** [comment]
same

**Comment by ghost** [comment]
Fixed, wait for next update.
