### ISSUE TITLE
Game keeps crashing, more than 10x in a row now. Unable to play the game.

### ISSUE THREAD

**Issue by lezterrnb** [Akebi-Private/Akebi-Issue-Tracker#56]
Games keeps crashing randomly, sometimes I'm able to play for about 3-5 minutes, mostly less than 2 minutes game will crash again. The crash is very arbitrary.  Sometimes while just exploring, sometimes after exiting a domain, sometimes just while attacking a monster. There are random instances of crashing since I purchased the game.
In addition, ESP update not saving on the json file after crash. 

My system Specs:
CPU: Intel(R) Core(TM) i7-9700K CPU @ 3.60GHz   3.60 GHz
RAM:  16 GB
GPU: GTX 1060 6GB
Windos: Windows 10 Pro 21H2
Installed on Samsung Evo 870 500GB

I did already a lot of troubleshooting:
Multiple restart, clean system crash dumps, run sfc /scannow, change folder location of AkebiGC, Verify integrity of files from the launcher, but still same issue. I'm unable to play the game that I paid for $19. 30 days subscription. This is really frustrating.

**Comment by GC-Ruth** [comment]
me too

**Comment by FaasHinRah** [comment]
Would help if you guys included what cheats you have enabled

**Comment by ghost** [comment]
What's features enabled?

**Comment by GC-Ruth** [comment]
kill aura,noclip,map teleport,esp,unlock fps

**Comment by GC-Ruth** [comment]
I don't know why, I used the original cfg.json file, which used to crash after a long run, but now it crashes after running for a few minutes, or half an hour, and the fastest one is still loading

**Comment by danzzzg1432** [comment]
I believe ESP is the issue.

**Comment by lezterrnb** [comment]
@CallowPurple  @FaasHinRah 
Here are the features I have used while experiencing the arbitrary crashes:

- ESP
- Interactive Map
- No clip
- Teleport
- UnlockFPS
- No skill cooldown
- God Mode (Conditional)
- Infinite Stamina
- Auto Loot
- Auto Seelie
- Mob vacuum
- Auto Talk (binded to RMB)
- No Fog
- Enable peeking
- Auto Cook & Fish

Hope this would be able to help in determining the issue. Thank you, team.

P.S. Still experiencing arbitrary crashes as of this writing. Can't even last inside the game not even at least 5 minutes, then auto crashes. Rinse and repeat. I tried a session with ESP turned off completely and still the same

**Comment by danzzzg1432** [comment]
> 

Message Ryujin on discord for a faster response

**Comment by lezterrnb** [comment]
> > 
> 
> Message Ryujin on discord for a faster response

I did since I was advised by Nitro yesterday, but unfortunately, he did not respond yesterday. Until now, as of this writing. >.<

**Comment by XcKiller** [comment]
ESP is the main issue of crashing.

**Comment by ghost** [comment]
Fixed in latest version.
