### ISSUE TITLE
The UI does not see which transfer point is selected and Chinese becomes a question mark

### ISSUE THREAD

**Issue by stig141** [Akebi-Private/Akebi-Issue-Tracker#63]
![7 4U23M_BLHS)B)~6GAQQ~B](https://user-images.githubusercontent.com/18372822/213404309-17ed109a-8ba2-4e56-898f-c15c1fdaceac.png)
![OJ%E$ZC B2_6ZEKS3%FFY45](https://user-images.githubusercontent.com/18372822/213404404-351d0ad4-62b7-4a50-9e21-d6ec5cf7947e.png)

**Comment by stig141** [comment]
The new UI is not as good as the old UI

**Comment by long385552** [comment]
Plus,the function seems to be less than previous version lol

**Comment by ghost** [comment]
Fixed in latest version.
