### ISSUE TITLE
Map Filter not showing

### ISSUE THREAD

**Issue by OneAutumnLeafXiao** [Akebi-Private/Akebi-Issue-Tracker#66]
![image](https://user-images.githubusercontent.com/122941077/213428959-d45f590c-76e2-42a8-9ac8-6a5dce219de7.png)

**Comment by fadillzzz** [comment]
You have to click on the bottom right corner and drag it to expand the window.

**Comment by OneAutumnLeafXiao** [comment]
omg I didnt even see it - thats stupid of me thanks!
