### ISSUE TITLE
`Feature request`: Speed up Seelie, Primal Ember, Pyramid Elevators...

### ISSUE THREAD

**Issue by SylverOmar** [Akebi-Private/Akebi-Issue-Tracker#72]
will it be possible to speed up the Seelie, Primal Ember, Pyramid Elevators and other mechanisms that only their animation is accelerated

**Comment by CallowPurple** [comment]
Partially duplicate to #101, linked to it.

**Comment by ghost** [comment]
Investigated this mechanic. Server sided, not possible to speed up.
