### ISSUE TITLE
Game crashes when you turn on god mode and finish one layer in Spiral Abyss

### ISSUE THREAD

**Issue by errqww** [Akebi-Private/Akebi-Issue-Tracker#83]
Game crashes when you turn on god mode and finish one layer in Spiral Abyss

**Comment by errqww** [comment]
maybe other patterns causes this, but when i turn off god mode it seems to be ok

**Comment by djdoolky76** [comment]
It seems pretty fine to me. I didn't encounter crash issues so far

**Comment by SylverOmar** [comment]
yeah me too, I didn't know it was god mode, it crashes from chamber to chamber of the same floor

**Comment by XcKiller** [comment]
try turning off the ESP when playing domaines/spiral abyss I think ESP is the main issue.

**Comment by ghost** [comment]
Fixed in latest version.
