### ISSUE TITLE
The program reported an error

### ISSUE THREAD

**Issue by James081105** [Akebi-Private/Akebi-Issue-Tracker#84]
I buy the 30-day Product and download the file but the program reported an error.It prompts "Filed connect to key sever. Error:Timeout was reached." and "Check your internet connection,or contact with support".But my internet was no problem.And I used VPN but it was useless.Please help me,thanks.

**Comment by FaasHinRah** [comment]
Servers are down.

**Comment by James081105** [comment]
> 
That's bad.
