### ISSUE TITLE
Interactive Map not working

### ISSUE THREAD

**Issue by djdoolky76** [Akebi-Private/Akebi-Issue-Tracker#86]
When i click the toggle arrow on an interactive map and map filters, there are no options or menu to activate, just a blank.
![image](https://user-images.githubusercontent.com/30578879/213512255-ec5322e2-3271-4185-b5d4-2a36d8419a57.png)

**Comment by SylverOmar** [comment]
resize the interactive map window from the bottom right corner

**Comment by djdoolky76** [comment]
> resize the interactive map window from the bottom right corner

Thank you it shows up now

![image](https://user-images.githubusercontent.com/30578879/213516915-78155f81-2a84-456d-a1d5-75a93004a271.png)
