### ISSUE TITLE
ESP detect objects abnormally

### ISSUE THREAD

**Issue by djdoolky76** [Akebi-Private/Akebi-Issue-Tracker#88]
Sometimes the checked marked target options for ESP, like chest and oculi, suddenly reset after you reopen the game/loader. you need to recheck them in the menu every time you restart, maybe because I use the old config from the past version but still works fine except for this feature.

![image](https://user-images.githubusercontent.com/30578879/213537589-1c76a2ff-1a15-48c6-971a-f1f4a47b4f58.png)

![image](https://user-images.githubusercontent.com/30578879/213537704-bfe0185d-7fec-4646-ba37-c9f9ba54abad.png)

**Comment by lezterrnb** [comment]
same scenario, same error as me

**Comment by a1047707793a** [comment]
me too, the porfie cant save esp settings

**Comment by ghost** [comment]
Duplicate of #101
