### ISSUE TITLE
`Bug Collection`: Bugs from china version game

### ISSUE THREAD

**Issue by qiyi09** [Akebi-Private/Akebi-Issue-Tracker#93]
[](url)A player from China，
Online real-time translation for translation
There may be some grammatical errors
~~First of all, the first problem I encountered when opening it is that it does not support Chinese.~~
~~Second, I found that the game crashed when cooking food~~
~~Third, when I transmit (map transmission), most of the time, it will probably be transmitted to a mountain in Liyue. It will not go where I want to go with my mouse~~
~~The fourth is the problem of plot acceleration, which has no effect~~
Fifth, when I automatically fish, the first time is normal. In the second time, I didn't open the new bait, but it seems that it will refresh itself and there is no place to close it. This will cause the fish I need to catch to be disturbed. I don't know how to close the Catch Delay (ms) script: moved to #102 
There are still some small strange bugs that I won't talk about. I'll talk to you in detail next time
Also, if you guys update, where do I need to go to download the latest version
I shared two videos in the comments section, and the remaining three were too large to send to you via email or link

If you need any help

zhang0010906@foxmail.com
This is my email
I posted a link to a shared network disk. You can try to download it. If you can't download it, you can send an email to my mailbox. I can send it to you by email
Blessings from a Chinese player

Link：https://pan.baidu.com/s/1AUZttLGC4xzbOKXzO6tM7Q?pwd=3ei8 
Extraction code：3ei8
@Taiga74164

**Comment by qiyi09** [comment]
https://user-images.githubusercontent.com/122051471/213603032-68a4677a-740e-4788-8473-e98217f7ebb2.mp4

**Comment by qiyi09** [comment]
https://user-images.githubusercontent.com/122051471/213603183-d253f1e9-3466-4f23-8a78-e6d14049bd1b.mp4

**Comment by ghost** [comment]
Most of bugs, already fixed, other moved to dedicated issues. Thanks for your help.
