### ISSUE TITLE
`UI`: Random multiplier bar too small to select desired single digit number

### ISSUE THREAD

**Issue by Zand1z33** [Akebi-Private/Akebi-Issue-Tracker#95]
Please modify this feature so that it is easier to select a desired number. Thanks in advance!

**Comment by ghost** [comment]
You can use RMB for now for specify correct value.

**Comment by Zand1z33** [comment]
Thank you for responding. Can you explain what and how to use the RMB?

**Comment by ghost** [comment]
Just press `Right Mouse Button` on slider.
