### ISSUE TITLE
`Launcher`: I can't open AkebiLanucher.exe correctly.I Need Your Help

### ISSUE THREAD

**Issue by Yuewan94** [Akebi-Private/Akebi-Issue-Tracker#98]
The following text comes from the translation software and may have some errors.
When I try to open the main program, a CMD interface will pop up, and the interface will prompt an error. The error is as follows。
error:183.
![QQ截图20230120105510](https://user-images.githubusercontent.com/123137587/213608325-1895ca71-b15a-410f-b207-f64567114f60.png)

When I try to open the main program again, a CMD interface will pop up, and the interface will prompt an error. The error is as follows
error:0.
![QQ截图20230120104652](https://user-images.githubusercontent.com/123137587/213607931-936b8079-9757-47e5-80c3-694621bb73b4.png)
I have paid for this tool and successfully received KEY, but obviously, I can't open the main program now, nor can I enter KEY to use it.
In addition, I also see that among other issues, it is mentioned that this tool does not have Chinese interface support. If this is true, please update the Chinese interface support as soon as possible.

**Comment by LookMomihaveaUsername** [comment]
1. Create a shortcut.
2. Open the shortcut properties
3. In the object field enter "-analog_inject" after GenshinImpact.exe
4. Run via the shortcut.

**Comment by Yuewan94** [comment]
> 1. 创建快捷方式。
> 2. 打开快捷方式属性
> 3. 在对象字段中，在“源神冲击”后输入“-analog_inject.exe
> 4. 通过快捷方式运行。
Thank you for your help.

I tried your method, but unfortunately, it didn't work.

My problem is that I can't open the akebigc client, instead of being unable to use it after successfully opening the client.

I still haven't solved the problem of Error183.

**Comment by LookMomihaveaUsername** [comment]
Try now. Maybe it got fixed it the update

**Comment by ghost** [comment]
> > 1. 创建快捷方式。
> > 2. 打开快捷方式属性
> > 3. 在对象字段中，在“源神冲击”后输入“-analog_inject.exe
> > 4. 通过快捷方式运行。
> >    Thank you for your help.
> 
> I tried your method, but unfortunately, it didn't work.
> 
> My problem is that I can't open the akebigc client, instead of being unable to use it after successfully opening the client.
> 
> I still haven't solved the problem of Error183.

You did something wrong, because your error can appear only when `-analog_inject` not used. Check our discord `faq` channel.
